// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9QXLC6E638WOxkY0H9wihhMVnMyAlSgk',
    appId: '1:247947105236:web:c33802b7d9719b11563c41',
    messagingSenderId: '247947105236',
    projectId: 'my-first-app-881b4',
    authDomain: 'my-first-app-881b4.firebaseapp.com',
    storageBucket: 'my-first-app-881b4.firebasestorage.app',
    measurementId: 'G-JJQG4K33VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDUiXD_OFM5Vir9MqIYDUOBRi8HF6PzM',
    appId: '1:247947105236:android:ee773389177dd54f563c41',
    messagingSenderId: '247947105236',
    projectId: 'my-first-app-881b4',
    storageBucket: 'my-first-app-881b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMimtJJmcd6DatS-gt3SKJko8DrSGlws',
    appId: '1:247947105236:ios:4dee09ed53b7837a563c41',
    messagingSenderId: '247947105236',
    projectId: 'my-first-app-881b4',
    storageBucket: 'my-first-app-881b4.firebasestorage.app',
    iosBundleId: 'com.example.zionshopings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUMimtJJmcd6DatS-gt3SKJko8DrSGlws',
    appId: '1:247947105236:ios:4dee09ed53b7837a563c41',
    messagingSenderId: '247947105236',
    projectId: 'my-first-app-881b4',
    storageBucket: 'my-first-app-881b4.firebasestorage.app',
    iosBundleId: 'com.example.zionshopings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9QXLC6E638WOxkY0H9wihhMVnMyAlSgk',
    appId: '1:247947105236:web:512b4053bb995bdb563c41',
    messagingSenderId: '247947105236',
    projectId: 'my-first-app-881b4',
    authDomain: 'my-first-app-881b4.firebaseapp.com',
    storageBucket: 'my-first-app-881b4.firebasestorage.app',
    measurementId: 'G-C0P2MX548M',
  );
}
